apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proxy
spec:
  rules:
    - host: web-app.obrol.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: interface
                port:
                  number: 3000
          - path: /web_app
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 3000

